### ISSUE TITLE
Yes but can you print me this

### ISSUE THREAD

**Issue by jfrux** [ch4se/OpenFrEON#1]
🖕

**Comment by ch4se** [comment]
like you want me to print you a middle finger? yeah I could probably do that.

**Comment by jszetoo** [comment]
What material should we should on Printing the case ?

**Comment by ch4se** [comment]
Should be printed in abs or petg

**Comment by jszetoo** [comment]
Thx, I have found the mention of ABS
Notice this model is little different  vs Eon 
it is for better cooling ?

**Comment by jszetoo** [comment]
do u have a picture of the mini PCB,  for the Fan.   
pls kindly email me ( halfbase@gmail.com )
I notice I do needed a cutout for it.

**Comment by jszetoo** [comment]
Hi,  forgot to ask a critical question !   
What's fill % would you suggest for this print ?  
Cheers ~

**Comment by ch4se** [comment]
25% should be sufficient, I recommend triangular infill, or hexagonal

**Comment by jszetoo** [comment]
2mm , 25% in fill ~ 
Which 3D print software, u perfer the most ?
For better routing & preview of support structure.

BTW, your design is very nice & low profile ~ 
Do u think the fan cover could be little longer. 😃🙂
